import type { Property } from "@/types/property";

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "prop-eastover-001",
    slug: "the-eastover-house",
    title: "The Eastover House",
    location: "Jackson, MS",
    description:
      "Experience luxury living in the heart of Jackson's prestigious Eastover neighborhood. This beautifully appointed 4-bedroom home offers an elegant retreat with modern amenities, spacious living areas, and a private backyard perfect for relaxation. Ideal for families, groups, or extended stays.",
    fullDescription: {
      space:
        "Spanning over 2,800 sq ft, the home features a gourmet kitchen with stainless steel appliances, a formal dining room seating 8, a cozy living room with a smart TV, and four well-appointed bedrooms each with premium bedding. The master suite includes an ensuite bathroom with a walk-in shower.",
      access:
        "Guests have full access to the entire home, including the backyard patio, washer/dryer, and two-car garage. Self check-in via smart lock with a private code provided before arrival.",
      neighborhood:
        "Eastover is one of Jackson's most sought-after neighborhoods, known for its tree-lined streets and stately homes. Minutes from restaurants, shopping, and the Mississippi Museum of Art. Easy access to I-55 and Jackson-Medgar Wiley Evers International Airport.",
      notes:
        "No smoking. No parties or events. Quiet hours 10 PM - 8 AM. Maximum occupancy 8 guests. Pets considered on a case-by-case basis with prior approval and a pet fee.",
    },
    photos: [
      {
        id: "photo-2",
        thumbnail: "/images/eastover/photo-2.jpg",
        full: "/images/eastover/photo-2.jpg",
        caption: "Front exterior",
      },
      {
        id: "photo-1",
        thumbnail: "/images/eastover/photo-1.jpg",
        full: "/images/eastover/photo-1.jpg",
        caption: "Living room",
      },
      {
        id: "photo-3",
        thumbnail: "/images/eastover/photo-3.jpg",
        full: "/images/eastover/photo-3.jpg",
        caption: "Open floor plan",
      },
      {
        id: "photo-4",
        thumbnail: "/images/eastover/photo-4.jpg",
        full: "/images/eastover/photo-4.jpg",
        caption: "Kitchen",
      },
      {
        id: "photo-5",
        thumbnail: "/images/eastover/photo-5.jpg",
        full: "/images/eastover/photo-5.jpg",
        caption: "Dining & kitchen",
      },
      {
        id: "photo-6",
        thumbnail: "/images/eastover/photo-6.jpg",
        full: "/images/eastover/photo-6.jpg",
        caption: "Fireplace & smart TV",
      },
      {
        id: "photo-7",
        thumbnail: "/images/eastover/photo-7.jpg",
        full: "/images/eastover/photo-7.jpg",
        caption: "Den",
      },
      {
        id: "photo-8",
        thumbnail: "/images/eastover/photo-8.jpg",
        full: "/images/eastover/photo-8.jpg",
        caption: "Master bedroom",
      },
    ],
    amenities: [
      "WiFi",
      "Kitchen",
      "Washer",
      "Dryer",
      "Free parking",
      "Smart TV",
      "Air conditioning",
      "Heating",
      "Iron",
      "Hair dryer",
      "Coffee maker",
      "Dishwasher",
      "Microwave",
      "Refrigerator",
      "Oven",
      "Toaster",
      "Smoke alarm",
      "Carbon monoxide alarm",
      "Fire extinguisher",
      "First aid kit",
      "Bed linens",
      "Towels",
      "Extra pillows and blankets",
      "Hangers",
      "Patio",
      "Backyard",
    ],
    guests: 6,
    bedrooms: 4,
    bathrooms: 2.5,
    beds: 5,
    pricing: {
      baseNightlyRate: 175,
      cleaningFee: 150,
      currency: "USD",
    },
    minStay: 3,
    maxGuests: 6,
  },
  {
    id: "prop-spacious-002",
    slug: "the-modern-retreat",
    title: "The Modern Retreat",
    location: "Jackson, MS",
    description:
      "Experience modern living in this brand-new 3-bedroom home in Jackson, MS. Step into a bright, open floor plan featuring a stylish living area, sleek kitchen with stainless steel appliances, and comfortable bedrooms with luxury bedding. Perfect for families, traveling professionals, or groups.",
    fullDescription: {
      space:
        "This brand-new home features an open floor plan with a spacious living room, a modern kitchen with stainless steel appliances and ample counter space, a dining area, and three well-appointed bedrooms with luxury bedding. The master suite includes a private bathroom.",
      access:
        "Guests have full access to the entire home, including the big backyard and private parking. Self check-in via smart lock with a private code provided before arrival.",
      neighborhood:
        "Located in a quiet Jackson neighborhood with easy access to dining and shopping options just minutes away. Convenient to major highways and Jackson-Medgar Wiley Evers International Airport.",
      notes:
        "No smoking. No parties or events. Quiet hours 10 PM - 8 AM. Maximum occupancy 7 guests.",
    },
    photos: [
      {
        id: "photo-s1",
        thumbnail: "/images/spacious-house/photo-1.jpg",
        full: "/images/spacious-house/photo-1.jpg",
        caption: "Front exterior",
      },
      {
        id: "photo-s2",
        thumbnail: "/images/spacious-house/photo-2.jpg",
        full: "/images/spacious-house/photo-2.jpg",
        caption: "Twin bedroom",
      },
      {
        id: "photo-s3",
        thumbnail: "/images/spacious-house/photo-3.jpg",
        full: "/images/spacious-house/photo-3.jpg",
        caption: "Dining room",
      },
      {
        id: "photo-s4",
        thumbnail: "/images/spacious-house/photo-4.jpg",
        full: "/images/spacious-house/photo-4.jpg",
        caption: "Bedroom",
      },
      {
        id: "photo-s5",
        thumbnail: "/images/spacious-house/photo-5.jpg",
        full: "/images/spacious-house/photo-5.jpg",
        caption: "Backyard patio",
      },
      {
        id: "photo-s6",
        thumbnail: "/images/spacious-house/photo-6.jpg",
        full: "/images/spacious-house/photo-6.jpg",
        caption: "Exterior with carport",
      },
    ],
    amenities: [
      "WiFi",
      "Kitchen",
      "Washer",
      "Dryer",
      "Free parking",
      "Smart TV",
      "Air conditioning",
      "Heating",
      "Iron",
      "Hair dryer",
      "Coffee maker",
      "Dishwasher",
      "Microwave",
      "Refrigerator",
      "Oven",
      "Smoke alarm",
      "Carbon monoxide alarm",
      "Fire extinguisher",
      "First aid kit",
      "Bed linens",
      "Towels",
      "Backyard",
    ],
    guests: 7,
    bedrooms: 3,
    bathrooms: 2,
    beds: 4,
    pricing: {
      baseNightlyRate: 150,
      cleaningFee: 100,
      currency: "USD",
    },
    minStay: 3,
    maxGuests: 7,
  },
  {
    id: "prop-pinelane-003",
    slug: "the-pine-lane-greenhouse",
    title: "The Pine Lane Greenhouse",
    location: "Jackson, MS",
    description:
      "A charming, pet-friendly retreat that blends vintage style with modern comfort. This spacious home in Jackson, MS is perfect for families or travelers seeking relaxation with convenient access to I-55, dining, shopping, and entertainment.",
    fullDescription: {
      space:
        "This charming home features a cozy living area with vintage-inspired decor, a fully equipped kitchen, comfortable bedrooms, and a welcoming atmosphere throughout. The blend of vintage style and modern amenities creates a unique and inviting space.",
      access:
        "Guests have full access to the entire home and private parking. Self check-in via smart lock with a private code provided before arrival. Pet-friendly — your furry friends are welcome!",
      neighborhood:
        "Located in a safe, quiet Jackson neighborhood with easy access to I-55. Dining, shopping, and entertainment options are just minutes away. Convenient to Jackson-Medgar Wiley Evers International Airport.",
      notes:
        "Pet-friendly property. No smoking. No parties or events. Quiet hours 10 PM - 8 AM. Maximum occupancy 5 guests.",
    },
    photos: [
      {
        id: "photo-p3",
        thumbnail: "/images/pine-lane/photo-3.jpg",
        full: "/images/pine-lane/photo-3.jpg",
        caption: "Front exterior",
      },
      {
        id: "photo-p8",
        thumbnail: "/images/pine-lane/photo-8.jpg",
        full: "/images/pine-lane/photo-8.jpg",
        caption: "Sunroom",
      },
      {
        id: "photo-p9",
        thumbnail: "/images/pine-lane/photo-9.jpg",
        full: "/images/pine-lane/photo-9.jpg",
        caption: "Living room",
      },
      {
        id: "photo-p2",
        thumbnail: "/images/pine-lane/photo-2.jpg",
        full: "/images/pine-lane/photo-2.jpg",
        caption: "Kitchen",
      },
      {
        id: "photo-p4",
        thumbnail: "/images/pine-lane/photo-4.jpg",
        full: "/images/pine-lane/photo-4.jpg",
        caption: "Butler's pantry",
      },
      {
        id: "photo-p10",
        thumbnail: "/images/pine-lane/photo-10.jpg",
        full: "/images/pine-lane/photo-10.jpg",
        caption: "Master bedroom",
      },
      {
        id: "photo-p5",
        thumbnail: "/images/pine-lane/photo-5.jpg",
        full: "/images/pine-lane/photo-5.jpg",
        caption: "Green bedroom",
      },
      {
        id: "photo-p6",
        thumbnail: "/images/pine-lane/photo-6.jpg",
        full: "/images/pine-lane/photo-6.jpg",
        caption: "Guest bedroom",
      },
      {
        id: "photo-p1",
        thumbnail: "/images/pine-lane/photo-1.jpg",
        full: "/images/pine-lane/photo-1.jpg",
        caption: "Backyard patio",
      },
      {
        id: "photo-p7",
        thumbnail: "/images/pine-lane/photo-7.jpg",
        full: "/images/pine-lane/photo-7.jpg",
        caption: "Outdoor dining",
      },
    ],
    amenities: [
      "WiFi",
      "Kitchen",
      "Washer",
      "Dryer",
      "Free parking",
      "Smart TV",
      "Air conditioning",
      "Heating",
      "Iron",
      "Hair dryer",
      "Coffee maker",
      "Microwave",
      "Refrigerator",
      "Smoke alarm",
      "Carbon monoxide alarm",
      "Fire extinguisher",
      "First aid kit",
      "Bed linens",
      "Towels",
      "Pet friendly",
    ],
    guests: 5,
    bedrooms: 3,
    bathrooms: 2,
    beds: 3,
    pricing: {
      baseNightlyRate: 165,
      cleaningFee: 85,
      currency: "USD",
    },
    minStay: 3,
    maxGuests: 5,
  },
];
